const { src, send, data } = require("../..");
const { WASD, array, randomHex, nullish, random, realtype, Math, time, formatDate, numberish, delay } = require("../../common");
const { log, path, fetch, listFiles, info, download, debug } = require("../../commonServer");
const { args } = require("../chat/chat");

module.exports.predicate = "!test";
module.exports.permission = false;
module.exports.execute = async (_reply, from, chatter, message, text, emote, reply) => {
    const u = WASD.unpack(badges)[0];
    for (const k in u) 
        data("external.ghabi.badge." + k, u[k]);
    const c = WASD.unpack(items)[0];
    for (const k in c) 
        data("external.ghabi.item." + k, c[k]);
    return [0, ""];
}

const badges = `{sysop {name sysop description "System Operator: This user is in charge of Ghabi's Forest's systems. Please contact us if you encounter any problems." icon "" permission 99} gardener {name gardener description "Gardener: This user is a designer of Ghabis." icon http://ghabisforest.kro.kr:9080/images/badge/gardener.png permission 99} moderator {name moderator description "Moderator: This user is a staff in Ghabi's Forest." icon http://ghabisforest.kro.kr:9080/images/badge/moderator.png permission 12} worldtreekey {name worldtreekey description "World Tree Key: This user has access to special contents." icon http://ghabisforest.kro.kr:9080/images/item/World%20Tree%20Key.png permission 10} pending {name pending description "Pending: This content is currently waiting for approval." icon "" permission 99} ghost {name ghost description "Ghost: This account is not owned by anyone, and is only there for data storage purposes." icon "" permission 99} blacklist {name blacklist description "Blacklisted: This content is now banned." icon "" permission 12} system {name system description "System Account: This account is not owned by anyone, and is only for system purposes." icon "" permission 99} discordHidden {name discordHidden description "Hide Discord: The owner of the account has chosen to hide their Discord account." icon "" permission 10} toyhouseHidden {name toyhouseHidden description "Hide Toyhou.se: The owner of the account has chosen to hide their Toyhou.se account." icon "" permission 10} workAlert {name workAlert description "Work Alert: This user will be pinged when their !work recharges." icon "" permission 10} hidden {name hidden description "Hidden: The owner of the page has hidden the page." icon "" permission 10} voided {name voided description "Voided: This character is no longer a Ghabi." icon "" permission 10} f2u {name f2u description "Free To Use: This character can be freely used for creations within the community." icon http://ghabisforest.kro.kr:9080/images/badge/f2u.png permission 10} myo {name myo description "Make Your Own: This character slot is not filled yet." icon http://ghabisforest.kro.kr:9080/images/badge/myo.png permission 10} fto {name fto description "First Time Owner: This account has not recieved a Ghabi yet." icon http://ghabisforest.kro.kr:9080/images/badge/fto.png permission 10} mascot {name mascot description "Mascot Character: This character represent the Ghabi community, and are free to draw within the community." icon http://ghabisforest.kro.kr:9080/images/badge/mascot.png permission 10} limited {name limited description "Limited: Admin only trait, has alternate forms" icon http://ghabisforest.kro.kr:9080/images/badge/limited.png permission 10}}`;
const items = `{"World Tree Key" {name "World Tree Key" acorn 30 icon http://ghabisforest.kro.kr:9080/images/item/World%20Tree%20Key.png type manual} Paint {name Paint acorn 200 icon http://ghabisforest.kro.kr:9080/images/item/Paint.png type item} Fertilizer {name Fertilizer acorn 500 icon http://ghabisforest.kro.kr:9080/images/item/Fertilizer.png type item} "Plant Food" {name "Plant Food" acorn 250 icon http://ghabisforest.kro.kr:9080/images/item/Plant%20Food.png type item} Teeth {name Teeth acorn 250 icon http://ghabisforest.kro.kr:9080/images/mutation/Teeth.png type mutation} "Paw Pad" {name "Paw Pad" acorn 250 icon http://ghabisforest.kro.kr:9080/images/mutation/Pawpad.png type mutation} "Multiple Eyes ∕ Cyclops" {name "Multiple Eyes / Cyclops" acorn 300 icon http://ghabisforest.kro.kr:9080/images/mutation/MultipleEyes.png type mutation} "Multiple Arms" {name "Multiple Arms" acorn 300 icon http://ghabisforest.kro.kr:9080/images/mutation/MultipleArms.png type mutation} "Multiple Wings" {name "Multiple Wings" acorn 450 icon http://ghabisforest.kro.kr:9080/images/mutation/MultipleWings.png type mutation} "No Eyes" {name "No Eyes" acorn 350 icon http://ghabisforest.kro.kr:9080/images/mutation/NoEyes.png type mutation} "Wing ∕ Tail Redesign" {name "Wing / Tail Redesign" acorn 350 icon http://ghabisforest.kro.kr:9080/images/mutation/Redesign.png type mutation} "Common MYO" {name "Common MYO" acorn 1200 icon http://ghabisforest.kro.kr:9080/images/MYO/common.png type myo}}`